/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import clientelocadora.conectaWS;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.domain.cliente.Locacao;

/**
 *
 * @author Paulo
 */
public class ListarLocacoes extends javax.swing.JFrame {

    /**
     * Creates new form ListarLocações
     */
    public ListarLocacoes() throws Exception {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLocacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnInserirLocacao = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaLocacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Cliente", "Valor", "Data da Locação", "Data de Devolução Prevista", "Data de Devolução Efetiva", "Multa"
            }
        ));
        jScrollPane1.setViewportView(tabelaLocacoes);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 3, 36)); // NOI18N
        jLabel1.setText("Locações");

        jMenu1.setText("Arquivo");

        btnInserirLocacao.setText("Inserir Locação");
        btnInserirLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirLocacaoActionPerformed(evt);
            }
        });
        jMenu1.add(btnInserirLocacao);

        jMenuItem2.setText("Cancelar Locação");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirLocacaoActionPerformed
        // TODO add your handling code here:
        InserirLocacao inserirLocacao = null;
        try {
            inserirLocacao = new InserirLocacao(this);
        } catch (Exception ex) {
            Logger.getLogger(ListarLocacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        inserirLocacao.setVisible(true);
    }//GEN-LAST:event_btnInserirLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarLocacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListarLocacoes().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ListarLocacoes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnInserirLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLocacoes;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabela() throws Exception {
       List locacoes = conectaWS.listarLocacoes();
       DefaultTableModel model = (DefaultTableModel) tabelaLocacoes.getModel(); 
       
       for(int i=0; i < model.getRowCount(); i ++){ //Apaga todas as linhas da tabela
           model.removeRow(i);
       }
       
       for(int i = 0; i < locacoes.size();i++){ //Preenche a tabela
            Object[] linha = new Object[7];
            Locacao l1 = (Locacao) locacoes.get(i);                    
            linha[0] = l1.getItem();
            linha[1] = l1.getCliente();
            linha[2] = l1.getValorCobrado();
            linha[3] = l1.getDtLocacao();
            linha[4] = l1.getDtDevolucaoPrevista();
            linha[5] = l1.getDtDevolucaoEfetiva();
            linha[6] = l1.getMultaCobrada();           
            model.addRow(linha);           
       }
       
    }
}
